baseURL = 'https://github.com/IanJCHEN/cdrl_ts'
languageCode = 'en-us'
title = 'Craft Design Reasearch Lab'
theme = 'hugo-creative-portfolio-theme'

[params]
  # Style options: default (pink), blue, green, pink, red, sea, violet
  # Use custom.css for your custom styling
  style = "green"
  description = "Describe your website"
  copyright = "&copy;2024 Craft Design Research Lab"
  sidebarAbout = [
    "Exploring tradition local craft with contemporary methodology in structural and computational design",
    "Hong Kong based research and design team"
  ]
  # Contact page
     # Since this template is static, the contact form uses www.formspree.io as a
     # proxy. The form makes a POST request to their servers to send the actual
     # email. Visitors can send up to a 1000 emails each month for free.
     #
     # What you need to do for the setup?
     #
     # - set your email address under 'email' below
     # - upload the generated site to your server
     # - send a dummy email yourself to confirm your account
     # - click the confirm link in the email from www.formspree.io
     # - you're done. Happy mailing!
  email = "you@yoursite.com"

    # Optional Matomo analytics (formerly piwik)
      # [params.analytics.matomo]
      #  URL = "https://stats.example.com"
      #  ID = "42"
      #  # Track all subdomains with "*.example.com" (Optional)
      #  domain = "www.example.com"
      #  # Optional integrity check hash
      #  hash = ""

  # Nav links in the side bar
  [[params.navlinks]]
  name = "Lab"
  url = "about/"
  home = true

  [[params.navlinks]]
  name = "Research"
  url = "research/"

  [[params.navlinks]]
  name = "Projects"
  url = "portfolio/"

  [[params.navlinks]]
  name = "Teaching"
  url = "events/"
  
  [[params.navlinks]]
  name = "People"
  url = "contact/"

  [params.social]
  facebook      = "full page or profile url in facebook"
  googleplus    = "full profile url in googleplus"
  email         = "email@example.com"
  twitter       = "full profile url in twitter"
  linkedin      = "full profile url in linkedin"
  stackoverflow = "full profile url in stackoverflow"
  instagram     = "https://www.instagram.com/craft_design_research_lab/"
  github        = "full profile url in github"
  gitlab        = "full profile url in gitlab"
  youtube       = "full profile url in youtube"
  whatsapp      = "wa.me service link"
